[package]
name = "md5check-rs"
version = "0.1.0"
description = "A add for checking md5"
authors = ["zrll"]
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6.5", features = [] }
async-channel = "2.3.1"
tokio = { version = "1.29.1", features = ["full"] }
md-5 = "0.10.6"
rfd = "0.14.1"
lazy_static = "1.4.0"
moka = "0.11.1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
